/* Static country list for the nomination form's country dropdown. */

export const COUNTRIES: readonly string[] = [
  "United Arab Emirates",
  "India",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Singapore",
  "Switzerland",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Ireland",
  "Portugal",
  "Austria",
  "Belgium",
  "Egypt",
  "Jordan",
  "Lebanon",
  "South Africa",
  "Nigeria",
  "Kenya",
  "China",
  "Japan",
  "South Korea",
  "Hong Kong",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Philippines",
  "Vietnam",
  "Sri Lanka",
  "Bangladesh",
  "Pakistan",
  "Nepal",
  "New Zealand",
  "Brazil",
  "Mexico",
  "Argentina",
  "Turkey",
  "Israel",
  "Morocco",
  "Maldives",
  "Other",
] as const;
