// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspection need a DIRECT (non-pooled) connection on
    // Neon. Falls back to DATABASE_URL if DIRECT_URL is not provided.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
